authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basket/urls.py
from django.urls import path

import basket.views as basket

app_name = 'basket'

urlpatterns = [
    path('', basket.basket, name='view'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('mens-shoes/', include('mainapp.urls', namespace='product')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('orders.urls', namespace='order')),
    path('order1/', include('orders.urls', namespace='order1')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('mens-shoes', views.mens_shoes, name='men'),
    path('womans-shoes', views.womans_shoes, name='woman'),
    path('product/<int:pk>/', views.product, name='product')
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderList.as_view(), name='orders_list'),
    path('create/', views.OrderItemsCreate.as_view(), name='order_create'),
]

mainapp/models.py
from django.db import models


class Sex(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDERS = (
        (MALE, 'Мужчина'),
        (FEMALE, 'Женщина'),
    )
    gender = models.CharField(max_length=1, choices=GENDERS, default='')

    def __str__(self):
        return self.gender


class SizeRange(models.Model):
    size_range = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.size_range)


class ListOfProduct(models.Model):
    title = models.TextField(verbose_name='заголовок')
    preview = models.CharField(max_length=230, verbose_name='Краткое описание',
                               default='', blank=True)
    description = models.TextField(verbose_name='описание', null=True,
                                   blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    img = models.TextField(verbose_name='Путь до фото', null=True, blank=True)
    sex = models.ForeignKey(Sex, on_delete=models.CASCADE, null=True,
                            blank=True)
    price = models.DecimalField(default=0, max_digits=7, decimal_places=2,
                                blank=True)
    size_range = models.ManyToManyField(SizeRange, blank=True)


    def get_size_range(self):
        # return ",".join([str(p) for p in self.size_range.all()])
        return self.size_range.all()

    def __str__(self):
        return f'Модель: {self.title}, Пол:  {self.sex},' \
               f' Размеры: {self.get_size_range()}'

    @staticmethod
    def get_items(user):
        return user.basket.select_related().order_by(
            'product__title')

mainapp/views.py
from django.shortcuts import render, get_object_or_404

from .models import ListOfProduct

ListOfProduct = ListOfProduct.objects.filter(is_active=True)
Men = ListOfProduct.filter(sex=1)
Woman = ListOfProduct.filter(sex=2)


def main(request):
    return render(request, 'mainapp/index.html')


def mens_shoes(request):
    return render(request, 'mainapp/mens_shoes.html',
                  {'ListOfProduct': Men})


def womans_shoes(request):
    return render(request, 'mainapp/womans-shoes.html',
                  {'ListOfProduct': Woman})


def product(request, pk):
    title = 'Продукты'
    content = {
        'ListOfProduct': ListOfProduct,
        'title': title,
        'ListOfProduct': get_object_or_404(ListOfProduct, pk=pk),
    }
    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/includes/inc_footer.html
<div class="navbar fixed-bottom" id="footer"
     style="background-color: #333a40;">
    <div class="container">
        <article class="text-light ">"Это больше, чем обувь. Это философия."
        </article>
        <div class="dropup">
            <a class="btn btn-secondary text-light border dropdown-toggle"
               href="#" role="button"
               id="dropdownMenuLink" data-bs-toggle="dropdown"
               aria-expanded="false">
                Контакты
            </a>

            <ul class="dropdown-menu dropdown-menu-dark"
                aria-labelledby="dropdownMenuLink">
                <li><a class="dropdown-item" href="#"><h6>Email: <small>example@mail.ru</small>
                </h6></a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#"><h6>Телефон: <small>8-800-555-1111</small>
                </h6></a></li>
            </ul>
        </div>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_header.html
<nav class="navbar navbar-expand-lg fixed-top"
     style="background-color: #333a40">
    <div class="container">
        <a class="navbar-brand" style="color: white;" href="/">BerezaShop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon bg-white"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent"
             style="width: 250px;">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="{% url 'main:men' %}"
                       class="nav-link btn btn-secondary text-light border "
                       style="margin-right: 2px; margin-bottom: 8px;">Мужские
                        кроссовки</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'main:woman' %}"
                       class="nav-link btn btn-secondary btn-lg text-light border"
                       style="margin-right: 2px;">Женские
                        кроссовки</a>
                </li>
                <li class="nav-item">
            </ul>
            <form>
                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'basket:view' %}"
                           class="nav-link btn btn-secondary text-light border"
                           style="margin-right: 2px; margin-bottom: 8px;">Корзина</a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown form-horizontal">
                            <a class="btn btn-secondary text-light border dropdown-toggle"
                               href="#" role="button"
                               id="dropdownMenuLink" data-bs-toggle="dropdown"
                               aria-expanded="false" style="padding: 8px;">
                                {{ user }}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark"
                                aria-labelledby="dropdownMenuLink">
                                <li>
                                    <a class="dropdown-item btn btn-secondary text-light"
                                       href="{% url 'auth:edit' %}">Редактировать</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item btn btn-secondary text-light"
                                       href="{% url 'order:orders_list' %}"
                                    >Мои заказы</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item btn btn-secondary text-light"
                                       href="{% url 'auth:logout' %}"
                                    >Выйти</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav" id="menu2">
                    <li class="nav-item">
                        <a href="{% url 'auth:login' %}"
                           class="nav-link btn btn-secondary text-light border"
                           style="margin-right: 2px;">Корзина</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'auth:login' %}"
                           class="nav-link btn btn-secondary text-light border"
                           style="margin: 0px 0px 0px 0px;">Личный
                            кабинет</a>
                    </li>
                </ul>
                {% endif %}
            </form>
        </div>
    </div>
</nav>