authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basket/urls.py
from django.urls import path

import basket.views as basket

app_name = 'basket'

urlpatterns = [
    path('', basket.basket, name='view'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('mens-shoes/', include('mainapp.urls', namespace='product')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('orders.urls', namespace='order')),
    path('order1/', include('orders.urls', namespace='order1')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('mens-shoes', views.mens_shoes, name='men'),
    path('womans-shoes', views.womans_shoes, name='woman'),
    path('product/<int:pk>/', views.product, name='product')
]

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class ShopUser(AbstractUser):
    age = models.PositiveIntegerField(verbose_name='возраст', default=18)


class ShopUserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'

    GENDER_CHOICES = (
        (MALE, 'Мужской'),
        (FEMALE, 'Женский'),
    )
    user = models.OneToOneField(ShopUser, unique=True, null=False,
                                db_index=True, on_delete=models.CASCADE)
    gender = models.CharField(
        verbose_name='пол', max_length=1, choices=GENDER_CHOICES,
        blank=True)


@receiver(post_save, sender=ShopUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        ShopUserProfile.objects.create(user=instance)


@receiver(post_save, sender=ShopUser)
def save_user_profile(sender, instance, **kwargs):
    instance.shopuserprofile.save()

authapp/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, \
    UserChangeForm
from django import forms
from authapp.models import ShopUser, ShopUserProfile


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = (
            'username', 'first_name', 'last_name', 'password1', 'password2',
            'email', 'age'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды")
        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('first_name', 'last_name', 'email', 'age')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserProfileEditForm(UserChangeForm):
    class Meta:
        model = ShopUserProfile
        fields = ('gender',)

    def __init__(self, *args, **kwargs):
        super(ShopUserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'password':
                field.widget = forms.HiddenInput()

authapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from authapp.forms import ShopUserRegisterForm, ShopUserLoginForm, \
    ShopUserProfileEditForm, ShopUserEditForm


def register(request):
    title = 'регистрания'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()
    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():

        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('mainapp:main'))

    content = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }

    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('mainapp:main'))


@transaction.atomic()
def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST,
                                     instance=request.user)
        profile_form = ShopUserProfileEditForm(
            request.POST, instance=request.user.shopuserprofile)

        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(
            instance=request.user.shopuserprofile)

    content = {'title': title,
               'edit_form': edit_form,
               'profile_form': profile_form}

    return render(request, 'authapp/edit.html', content)

authapp/templates/authapp/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>

<body>
{% block header %}
{% include 'mainapp/includes/inc_header.html' %}
{% endblock %}

{% block content %}

{% endblock %}


{% block footer %}
{% include 'mainapp/includes/inc_footer.html' %}
{% endblock %}
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block title %}Редактирование{% endblock %}

{% block content %}
<div class="container">
    <div class="container form-group row" style="margin-top: 80px; margin-bottom: 60px;">
        <div>
            <div><h3>Редактирование профиля</h3></div>
            <form class="col-lg-offset-4  form-horizontal "
                  action="{% url 'auth:edit' %}" method="post">
                {% csrf_token %}
                {{ edit_form.as_p }}
                {{ profile_form.as_p }}
                <input class="btn btn-secondary text-light border"
                       type="submit" value="сохранить">

                <button class="btn btn-secondary text-light border">
                    <a style="color: white; text-decoration: none;"
                       href="{% url 'mainapp:main' %}" class="">
                        на главную
                    </a>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block title %}Авторизация{% endblock %}
{% block content %}
<div class="container" style="margin-top: 80px; margin-bottom: 120px;">
    <div class="login">
        <div class="h2 text-center head">Вход в систему</div>

        <form class="form-horizontal"
              action="{% url 'auth:login' %}" method="post">
            {% csrf_token %}
            {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
            {% endif %}
            {{ login_form.as_p }}
            <br>
            <input class="btn btn-secondary text-light border" type="submit" value="Войти" style="margin-bottom: 8px;">
        </form>
        <button class="btn btn-secondary text-light border">
            <a style="text-decoration: none; color: white" href="{% url 'auth:register' %}">
                Зарегистрироваться
            </a>
        </button>
        <button class="btn btn-secondary text-light border">
            <a style="text-decoration: none; color: white"
               href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
                Вход через ВКонтакте
            </a>
        </button>

    </div>
</div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="container" style="margin-top: 80px; margin-bottom: 120px;">
    <div class="login">
        <div class="h2 text-center head">
            Регистрация нового пользователя
        </div>
        <form class="form-horizontal"
              action="{% url 'auth:register' %}" method="post">
            {% csrf_token %}
            {{ register_form.as_p }}
            <input class="form_control btn btn-secondary text-light border"
                   type="submit" value="зарегистрироваться">
        </form>
    </div>
</div>
{% endblock %}