basket/urls.py
from django.urls import path

import basket.views as basket

app_name = 'basket'

urlpatterns = [
    path('', basket.basket, name='view'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('mens-shoes/', include('mainapp.urls', namespace='product')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('orders.urls', namespace='order')),
    path('order1/', include('orders.urls', namespace='order1')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('mens-shoes', views.mens_shoes, name='men'),
    path('womans-shoes', views.womans_shoes, name='woman'),
    path('product/<int:pk>/', views.product, name='product')
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderList.as_view(), name='orders_list'),
    path('create/', views.OrderItemsCreate.as_view(), name='order_create'),
]

basket/models.py
from django.db import models
from django.conf import settings
from mainapp.models import ListOfProduct, SizeRange, Sex


class Basket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='basket')
    product = models.ForeignKey(ListOfProduct,
                                on_delete=models.CASCADE)
    add_datetime = models.DateTimeField(verbose_name='время',
                                        auto_now_add=True)
    size = models.CharField(max_length=200, verbose_name='Размер', blank=True,
                            null=True)

    def __str__(self):
        return self.product.title

    @property
    def cost(self):
        return self.product.price * len(self.size.split(','))

    @property
    def total_cost(self):
        product = Basket.objects.filter(user=self.user)
        total_cost = sum(map(lambda x: x.cost, product))
        return total_cost

    @property
    def count_size(self):
        return len(self.size.split(','))

    @staticmethod
    def get_items(user):
        return user.basket.select_related().order_by(
            'product__title')

basket/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from basket.models import Basket
from mainapp.models import ListOfProduct, SizeRange


@login_required
def basket(request):
    basket_items = Basket.objects.filter(
        user=request.user).order_by('product__title')
    content = {
        'basket_items': basket_items,
    }
    return render(request, 'basket/basket.html', content)


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('main:men',
                                            args=[pk]))

    if request.method == 'POST':
        size = request.POST.copy().pop('size')
        sizes = ','.join(size)
    product = get_object_or_404(ListOfProduct, pk=pk)
    basket = Basket.objects.filter(user=request.user,
                                   product=product).first()
    if not basket:
        basket = Basket(user=request.user, product=product, size=sizes)
    basket.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

basket/templates/basket/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>

<body>
{% block header %}
{% include 'mainapp/includes/inc_header.html' %}
{% endblock %}

<div class="container" style="margin-top: 80px;">
    <div class="h2 text-center head">
        Ваша корзина:
        {% if user.first_name %}
            {{ user.first_name }}
            {{ user.last_name }}
        {% else %}
            Пользователь
        {% endif %}
    </div>
</div>

{% block list %}
{% endblock %}

{% block content %}
{% endblock %}




{% block footer %}
{% include 'mainapp/includes/inc_footer.html' %}
{% endblock %}

<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

basket/templates/basket/basket.html
{% extends 'basket/base.html' %}
{% load static %}
{% block title %}Корзина{% endblock %}
{% block list %}
{% for item in basket_items %}
<div class="container">
    <div class="card col-xl-8 col-md-12 col-lg-10" id="card-basket">
        <div class="row g-0">
            <div class="col-md-5">
                <img id="basket_cart" src="/static/{{ item.product.img }}"
                     class="img-fluid rounded-start" alt="Photo">
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{ item.product.title }}</h5>
                    <p class="card-text">Размер: <b>{{ item.size }}</b></p>
                    <p class="card-text">Цена за единицу: <b>
                        {{ item.product.price }}</b>&nbspруб</p>
                    <p class="card-text">Кол-во: <strong>{{ item.count_size }}
                    </strong></p>
                    <button class="btn btn-danger btn-sm">
                        <a id="cart_del"
                           style="color: white; text-decoration: none"
                           href="{% url 'basket:remove' item.pk %}"
                           class="">удалить</a>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% if basket_items %}
<div class="container " style="margin-bottom: 50px; margin-top: 50px;">
    <p>Всего к оплате: <strong>{{ basket_items.first.total_cost }}</strong>
        рублей.</p>
    <button class="btn btn-secondary text-light border">
        <a style="text-decoration: none; color: white"
           href="{% url 'order:order_create' %}">Перейти к покупке</a>
    </button>
{% else %}
{% endif %}
{% endblock %}

{% block content %}
<div class="container" style="padding: 0px;">
    <button class="btn btn-secondary text-light border"
            style="margin-bottom: 70px; margin-top: 20px;">
        <a style="text-decoration: none; color: white"
           href="{% url 'main:main' %}">
            на главную
        </a>
    </button>
</div>
{% endblock %}