authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basket/urls.py
from django.urls import path

import basket.views as basket

app_name = 'basket'

urlpatterns = [
    path('', basket.basket, name='view'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('mens-shoes/', include('mainapp.urls', namespace='product')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('order/', include('orders.urls', namespace='order')),
    path('order1/', include('orders.urls', namespace='order1')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('mens-shoes', views.mens_shoes, name='men'),
    path('womans-shoes', views.womans_shoes, name='woman'),
    path('product/<int:pk>/', views.product, name='product')
]

mainapp/models.py
from django.db import models


class Sex(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDERS = (
        (MALE, 'Мужчина'),
        (FEMALE, 'Женщина'),
    )
    gender = models.CharField(max_length=1, choices=GENDERS, default='')

    def __str__(self):
        return self.gender


class SizeRange(models.Model):
    size_range = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.size_range)


class ListOfProduct(models.Model):
    title = models.TextField(verbose_name='заголовок')
    preview = models.CharField(max_length=230, verbose_name='Краткое описание',
                               default='', blank=True)
    description = models.TextField(verbose_name='описание', null=True,
                                   blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    img = models.TextField(verbose_name='Путь до фото', null=True, blank=True)
    sex = models.ForeignKey(Sex, on_delete=models.CASCADE, null=True,
                            blank=True)
    price = models.DecimalField(default=0, max_digits=7, decimal_places=2,
                                blank=True)
    size_range = models.ManyToManyField(SizeRange, blank=True)


    def get_size_range(self):
        # return ",".join([str(p) for p in self.size_range.all()])
        return self.size_range.all()

    def __str__(self):
        return f'Модель: {self.title}, Пол:  {self.sex},' \
               f' Размеры: {self.get_size_range()}'

    @staticmethod
    def get_items(user):
        return user.basket.select_related().order_by(
            'product__title')

mainapp/views.py
from django.shortcuts import render, get_object_or_404

from .models import ListOfProduct

ListOfProduct = ListOfProduct.objects.filter(is_active=True)
Men = ListOfProduct.filter(sex=1)
Woman = ListOfProduct.filter(sex=2)


def main(request):
    return render(request, 'mainapp/index.html')


def mens_shoes(request):
    return render(request, 'mainapp/mens_shoes.html',
                  {'ListOfProduct': Men})


def womans_shoes(request):
    return render(request, 'mainapp/womans-shoes.html',
                  {'ListOfProduct': Woman})


def product(request, pk):
    title = 'Продукты'
    content = {
        'ListOfProduct': ListOfProduct,
        'title': title,
        'ListOfProduct': get_object_or_404(ListOfProduct, pk=pk),
    }
    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>

<body>
{% block header %}
{% include 'mainapp/includes/inc_header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block list %}

{% endblock %}


{% block footer %}
{% include 'mainapp/includes/inc_footer.html' %}
{% endblock %}

<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

mainapp/templates/mainapp/card2.html
{% load static %}


<div class="container-xl" style="margin-top: 100px; margin-bottom: 120px;">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-3" style="margin-bottom: 120px;">
        {% for el in ListOfProduct %}
        {% csrf_token %}
        <div class="col" id="col">
            <div class="card" id="card">
                <div class="card-img">
                    <a href="{% url 'product:product' el.id %}"><img
                            class="img-card"
                            src="/static/{{ el.img }}"
                            alt="Ошибка загрузки фото"></a>
                </div>
                <div class="card-body">
                    <h4 class="title">{{ el.title }}</h4>
                    <p class="card-text">{{el.preview }}</p>
                </div>

                <div class="card-footer d-flex justify-content-between">
                    <h3>{{ el.price }}</h3>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}Bereza-shop{% endblock %}

{% block content %}
<div class="main" id="main">
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="3000">
                <img src="{% static 'img/1.jpg' %}" class="d-block w-100" alt="Кроссовки nike">
            </div>
            <div class="carousel-item" data-bs-interval="3000">
                <img src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="Кроссовки nike">
            </div>
            <div class="carousel-item" data-bs-interval="3000">
                <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="Кроссовки nike">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Предыдущий</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Следующий</span>
        </button>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/mens_shoes.html
{% extends 'mainapp/base.html' %}
{% block title %}Мужские кроссовки{% endblock %}

{% block content %}
{% csrf_token %}
{% include 'mainapp/card2.html' %}
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}Описание товара{% endblock %}

{% block content %}

<div class="container-lg" style="margin-top: 100px; margin-bottom: 120px;"
     xmlns="http://www.w3.org/1999/html">
    <div class="card col-sm-auto">
        <div class="d-flex justify-content-center">
            <img id="product-img" src="/static/{{ListOfProduct.img}}"
                 class="card-img-top"
                 alt="Фото товара">
        </div>
        <div class="card-body" style="min-height: 50px;">
            <h5 class="card-title">{{ ListOfProduct.title }}</h5>
            <p class="card-text">{{ ListOfProduct.description }}</p>
            <h5>Цена: {{ ListOfProduct.price }}</h5>
        </div>
        {% if user.is_authenticated %}
        <div class="input-group"
             style="padding: 16px;">
            <div class="d-flex align-items-center">
                <h5 style="margin-right: 10px;">Выберите размер (EU):</h5>
            </div>
            <form action="{% url 'basket:add' ListOfProduct.pk %}"
                  class="col-lg-offset-4" method="POST">
                {% csrf_token %}
                {% for el in ListOfProduct.get_size_range %}
                <input type="checkbox" id="{{ el }}" value="{{ el }}"
                       name="size">
                <label for="{{ el }}">{{ el }}</label>
                {% endfor %}
                <input class="btn btn-secondary text-light border"
                       type="submit" id="product-button"
                       value="Добавить в корзину" disabled>
            </form>
            {% else %}
            <div class="container"  >
                <b>Для покупки авторизуйтесь</b>
                <button class="btn btn-secondary text-light border"><a
                        href="{% url 'auth:login' %}"
                        style="color: white; text-decoration: none">Вход / Регистрация</a>
                </button>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/36.js' %}"></script>
<script type="text/javascript" src="{% static 'js/37.js' %}"></script>
<script type="text/javascript" src="{% static 'js/38.js' %}"></script>
<script type="text/javascript" src="{% static 'js/39.js' %}"></script>
<script type="text/javascript" src="{% static 'js/40.js' %}"></script>
<script type="text/javascript" src="{% static 'js/41.js' %}"></script>
<script type="text/javascript" src="{% static 'js/42.js' %}"></script>
<script type="text/javascript" src="{% static 'js/43.js' %}"></script>
<script type="text/javascript" src="{% static 'js/44.js' %}"></script>
<script type="text/javascript" src="{% static 'js/45.js' %}"></script>
<script type="text/javascript" src="{% static 'js/46.js' %}"></script>

{% endblock %}

mainapp/templates/mainapp/womans-shoes.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}Женские кроссовки{% endblock %}

{% block content %}
{% csrf_token %}
{% include 'mainapp/card2.html' %}
{% endblock %}